name: Sync to Fork (Repo B)

on:
  push:
    branches:
      - prod

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_KEY }}" > id_rsa
          chmod 600 id_rsa
          ssh-keyscan github.com >> known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Sync Branches
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add id_rsa
          git remote add club-website git@github.com:velocitatem/club-website.git
          git push repoB ${{ github.ref }}
